<?php

return array (
  'name' => 'VV跑腿',
  'beian' => '',
  'cdnurl' => '',
  'version' => '1.0.1',
  'timezone' => 'Asia/Shanghai',
  'forbiddenip' => '',
  'languages' => 
  array (
    'backend' => 'zh-cn',
    'frontend' => 'zh-cn',
  ),
  'fixedpage' => 'dashboard',
  'categorytype' => 
  array (
    'default' => 'Default',
    'page' => 'Page',
    'article' => 'Article',
    'test' => 'Test',
  ),
  'configgroup' => 
  array (
    'basic' => 'Basic',
    'vvpt' => 'Vvpt',
  ),
  'mail_type' => '1',
  'mail_smtp_host' => 'smtp.qq.com',
  'mail_smtp_port' => '465',
  'mail_smtp_user' => '10000',
  'mail_smtp_pass' => 'password',
  'mail_verify_type' => '2',
  'mail_from' => '10000@qq.com',
  'sms_appkey' => '123213213',
  'sms_secretKey' => '',
  'sms_product' => '',
  'wx_appid' => '66',
  'wx_userid' => '',
  'wx_secret' => '',
  'ali_user' => '661111',
  'ali_pid' => '',
  'ali_key' => '',
  'take_percent' => '20',
  'weather' => '5',
  'two_km' => '8',
  'three_km' => '12',
  'three_ten_km' => '1',
  'ten_thirty_km' => '2',
  'over_thirty_km' => '3',
  'lower_twentyfive_kg' => '0',
  'twentysix_thirty_kg' => '5',
  'thirtyone_forty_kg' => '10',
  'over_forty_kg' => '5',
  'lineup_start_price' => '10',
  'lineup_one_ten_price' => '10',
  'lineup_delayed_price' => '10',
  'front_night' => '4',
  'back_night' => '8',
  'subscription_price' => '5',
  'is_extension' => '0',
  'is_weather' => '0',
);